on: [push]
name: build
jobs:
  build-test:
    strategy:
      matrix:
        go-version: ["stable", "oldstable"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          persist-credentials: false
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # https://github.com/actions/setup-go/releases/tag/v6.3.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod download
      - name: Test with Go
        # run: go test -cover -json ./... > TestResults-${{ matrix.os }}-${{ matrix.go-version }}.json
        run: go test -cover ./...
      # - name: Upload Go test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Go-results-${{ matrix.os }}-${{ matrix.go-version }}
      #     path: TestResults-${{ matrix.os }}-${{ matrix.go-version }}.json
      # - name: Update coverage report
      #   uses: ncruces/go-coverage-report@v0
      #   with:
      #     report: true
      #     chart: true
      #     amend: true
      #   if: |
      #     matrix.os == 'ubuntu-latest' &&
      #     github.event_name == 'push'
      #   continue-on-error: true
